[relabel]
allow-unauthenticated = [
    "A-*",
    "C-*",
    "D-*",
    "E-*",
    "F-*",
    "I-*",
    "L-*",
    "NLL-*",
    "O-*",
    "PG-*",
    "S-*",
    "T-*",
    "WG-*",
    "-Z*",
    "beta-nominated",
    "const-hack",
    "llvm-*",
    "needs-fcp",
    "relnotes",
    "requires-*",
    "regression-*",
    "rla-*",
    "perf-*",
    "AsyncAwait-OnDeck",
    "needs-triage",
    "has-merge-commits",
]

