name: Test Code

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: asterinas/asterinas:0.13.0
    steps:
      - run: echo "Running in asterinas/asterinas:0.13.0"
      - uses: actions/checkout@v4

      - name: Check Asterinas
        id: check
        run: make check
    
      - name: Check OSDK
        id: check_osdk
        run: make check_osdk

  compilation:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: asterinas/asterinas:0.13.0
    steps:
      - run: echo "Running in asterinas/asterinas:0.13.0"

      - uses: actions/checkout@v4

      # The compilation test builds the project with all features enabled.
      # In contrast, subsequent tests may choose to enable select features.
      - name: Compilation
        id: compilation
        run: make build FEATURES=all

  unit-test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: 
      image: asterinas/asterinas:0.13.0
      options: --device=/dev/kvm --privileged
    steps:
      - run: echo "Running in asterinas/asterinas:0.13.0"

      - uses: actions/checkout@v4

      - name: Usermode Unit test
        id: usermode_unit_test
        run: make test

      - name: Ktest Unit Test
        id: ktest_unit_test
        run: make ktest NETDEV=tap

      # Github's actions/checkout@v4 will result in a new user (not root) 
      # and thus not using the Rust environment we set up in the container. 
      # So the RUSTUP_HOME needs to be set here. 
      - name: Unit test
        id: unit_test
        run: RUSTUP_HOME=/root/.rustup make test_osdk

      # TODO: add component check.