name: Integration Test Template

on:
  workflow_call:
    inputs:
      test_id:
        required: true
        type: string
      auto_test:
        required: true
        type: string
      release:
        required: true
        type: boolean
      enable_kvm:
        required: true
        type: boolean
      intel_tdx:
        required: true
        type: boolean
      smp:
        required: false
        type: number
        default: 1
      netdev:
        required: false
        type: string
        default: 'user'
      scheme:  
        required: false
        type: string
        default: ''
      extra_blocklists:
        required: false
        type: string
        default: ''
      syscall_test_dir:
        required: false
        type: string
        default: '/tmp'
      boot_protocol:
        required: false
        type: string
        default: 'linux-efi-handover64'
      runs_on:
        required: false
        type: string
        default: 'ubuntu-latest'
      timeout_minutes:
        required: false
        type: number
        default: 15
      container_image:
        required: false
        type: string
        default: 'asterinas/asterinas:0.13.0'

jobs:
  integration-test:
    runs-on: ${{ inputs.runs_on }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    env:
      RUSTUP_DIST_SERVER: ${{ inputs.intel_tdx && 'https://mirrors.ustc.edu.cn/rust-static' || '' }}
      RUSTUP_UPDATE_ROOT: ${{ inputs.intel_tdx && 'https://mirrors.ustc.edu.cn/rust-static/rustup' || '' }}
    container:
      image: ${{ inputs.container_image }}
      options: --device=/dev/kvm --privileged
    steps:
      - uses: actions/checkout@v4
      
      - name: Initialize environment  
        if: inputs.intel_tdx
        run: |
          chmod +x test/benchmark/bench_linux_and_aster.sh
          git config --global --add safe.directory /__w/asterinas/asterinas
          git config --global http.sslVerify false
          git config --global http.version HTTP/1.1

      - name: Setup environment
        run: |
          echo "Running test ${{ inputs.test_id }}"
          echo "Container image: ${{ inputs.container_image }}"
          
      - name: Run Test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: |
            make run \
              AUTO_TEST=${{ inputs.auto_test }} \
              RELEASE=${{ inputs.release && 1 || 0 }} \
              ENABLE_KVM=${{ inputs.enable_kvm && 1 || 0 }} \
              INTEL_TDX=${{ inputs.intel_tdx && 1 || 0 }} \
              SMP=${{ inputs.smp }} \
              NETDEV=${{ inputs.netdev }} \
              SCHEME=${{ inputs.scheme }} \  
              EXTRA_BLOCKLISTS_DIRS=${{ inputs.extra_blocklists }} \
              SYSCALL_TEST_DIR=${{ inputs.syscall_test_dir }} \
              BOOT_PROTOCOL=${{ inputs.boot_protocol }}
