name: Test Asterinas on x86

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration-test:
    uses: ./.github/workflows/backend_integration.yml
    strategy:
      matrix:
        test_id:
          # Boot 
          - 'boot_mb'
          - 'boot_legacy32'
          - 'boot_mb2_smp4'

          # Syscall 
          - 'syscall_debug'
          - 'syscall_at_ext2_microvm'
          - 'syscall_at_ext2_iommu_debug'
          - 'syscall_at_exfat_mb2_nokvm'
          - 'syscall_mb2_smp4'

          # General 
          - 'test_efi'
          - 'test_mb2_smp4'
      fail-fast: false
    with:
      test_id: ${{ matrix.test_id }}
      auto_test: ${{ startsWith(matrix.test_id, 'boot') && 'boot' ||
        startsWith(matrix.test_id, 'syscall') && 'syscall' ||
        startsWith(matrix.test_id, 'test') && 'test' }}
      release: ${{ !contains(matrix.test_id, '_debug') }}
      enable_kvm: ${{ !contains(matrix.test_id, 'nokvm') }}
      intel_tdx: ${{ contains(matrix.test_id, 'tdx') }}
      smp: ${{ contains(matrix.test_id, 'smp4') && 4 || contains(matrix.test_id, 'smp') && 2 || 1 }}
      netdev: 'tap'
      scheme: ${{ contains(matrix.test_id, 'microvm') && 'microvm' || contains(matrix.test_id, 'iommu') && 'iommu' || '' }}
      extra_blocklists: ${{ contains(matrix.test_id, 'exfat') && 'blocklists.exfat' || '' }}
      syscall_test_dir: ${{ contains(matrix.test_id, 'at_ext2') && '/ext2' ||
        contains(matrix.test_id, 'at_exfat') && '/exfat' || '/tmp' }}
      boot_protocol: ${{ contains(matrix.test_id, 'mb2') && 'multiboot2' || 
        contains(matrix.test_id, 'mb') && 'multiboot' || 
        contains(matrix.test_id, 'legacy32') && 'linux-legacy32' || 'linux-efi-handover64' }}
      container_image: 'asterinas/asterinas:0.13.0'
      runs_on: 'ubuntu-latest'
